name: suncoopatt
description: "Shift Management and Staff Time Tracking System"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  
  # Backend & Auth
  supabase_flutter: ^2.1.0
  
  # JSON & Serialization
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  
  # UI & Calendar
  syncfusion_flutter_calendar: ^24.1.41
  table_calendar: ^3.0.9
  
  # Location & WiFi
  geolocator: ^10.1.0
  wifi_info_flutter: ^2.0.2
  permission_handler: ^11.1.0
  
  # Security & Device Info
  device_info_plus: ^9.1.1
  safe_device: ^1.1.4
  
  # Utilities
  intl: ^0.19.0
  go_router: ^12.1.3
  shared_preferences: ^2.2.2
  connectivity_plus: ^5.0.2
  
  # UI Components & Animations
  flutter_spinkit: ^5.2.0
  cached_network_image: ^3.3.0
  google_fonts: ^6.1.0
  flutter_animate: ^4.3.0
  lottie: ^2.7.0
  
  # Theme Management
  adaptive_theme: ^3.4.1
  
  # Enhanced UI
  flutter_staggered_animations: ^1.1.1
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Code Generation
  build_runner: ^2.4.7
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.9

flutter:
  uses-material-design: true
  
  # Assets placeholder for future use
  # assets:
  #   - assets/images/
  #   - assets/icons/
